version: '2'
services:
  amqp:
    image: 'rabbitmq'
    ports:
      - '5672:5672'

  supervisor:
    build:
      context: './supervisor'
    environment:
      - 'S3_BUCKET="montage-dag"'
      - 'S3_PATH="0.10/input"'
      - 'REDIS_URL=redis:redis'
      - 'AMQP_URL=amqp://amqp:5672'
    depends_on:
      - redis
      - amqp

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  worker:
    build:
      context: './worker'
    environment:
      - 'AWS_ACCESS_KEY_ID="fooo"'
      - 'AWS_SECRET_ACCESS_KEY="fooo"'
      - 'AMQP_URL=amqp://amqp:5672'
    depends_on:
      - amqp
      - supervisor
