amqp_url: amqp://admin:insecure@<%= ENV['AMQP_1_PORT_5672_TCP_ADDR'] %>:<%= ENV['AMQP_1_PORT_5672_TCP_PORT']%>
threads: <%= Executor::cpu_count %>
storage: cloud
:cloud_storage:
  :aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  :aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  :region: "eu-west-1"


